import { useState, useSyncExternalStore } from 'react';
import type { AiController } from '../../../ai/aiController';
import type { PromptPreset } from '../../../ai/types';
import { restorePreset, builtInPresets } from '../../../ai/presets';
import type { MessageKey } from '../../../i18n/messages';
import { useT } from '../../../i18n/I18nProvider';
import { Parameters } from '../ModelSelector';
import { defaultProfile } from '../../../ai/profiles';
export function AiPresetsSection({controller}:{controller:AiController}){
 const t=useT(),state=useSyncExternalStore(controller.subscribe,controller.getState),[draft,setDraft]=useState<PromptPreset|null>(null);
 const run=(p:Promise<unknown>)=>void p.catch(e=>controller.report(e));
 return <fieldset className="ai-settings"><legend>{t('ai.managePresets')}</legend><div className="ai-bar">{[...state.presets].sort((a,b)=>a.order-b.order).map(p=><button key={p.id} onClick={()=>setDraft({...p})}>{p.name||t(`ai.preset.${p.builtInId}` as MessageKey)}</button>)}<button onClick={()=>setDraft({...builtInPresets()[0],id:crypto.randomUUID(),builtInId:undefined,name:'',instructions:'',order:state.presets.length})}>{t('ai.create')}</button></div>{draft&&<><label>{t('ai.name')}<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{t('ai.instructions')}<textarea value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})}/></label><label>{t('ai.targetLanguage')}<input value={draft.variables?.targetLanguage??''} onChange={e=>setDraft({...draft,variables:{targetLanguage:e.target.value}})}/></label><label>{t('ai.view.diff')}<select value={draft.view} onChange={e=>setDraft({...draft,view:e.target.value as 'diff'|'side'})}>{(['diff','side']as const).map(v=><option key={v} value={v}>{t(`ai.view.${v}`)}</option>)}</select></label><label>{t('ai.strategy')}<select value={draft.strategy} onChange={e=>setDraft({...draft,strategy:e.target.value as 'whole'|'chunked'})}>{(['whole','chunked']as const).map(v=><option key={v} value={v}>{t(`ai.strategy.${v}`)}</option>)}</select></label><label>{t('ai.frontmatter')}<select value={draft.frontmatter} onChange={e=>setDraft({...draft,frontmatter:e.target.value as 'keep'|'include'})}>{(['keep','include']as const).map(v=><option key={v} value={v}>{t(`ai.frontmatter.${v}`)}</option>)}</select></label><label>{t('ai.order')}<input type="number" min="0" value={draft.order} onChange={e=>setDraft({...draft,order:Math.max(0,Number(e.target.value)||0)})}/></label><label><input type="checkbox" checked={draft.hidden} onChange={e=>setDraft({...draft,hidden:e.target.checked})}/>{t('ai.hidden')}</label><Parameters profile={defaultProfile()} value={draft.params||{}} onChange={params=>setDraft({...draft,params})}/><div className="ai-bar"><button onClick={()=>run(controller.savePreset(draft))}>{t('ai.save')}</button><button onClick={()=>setDraft({...draft,id:crypto.randomUUID(),builtInId:undefined})}>{t('ai.duplicate')}</button>{draft.builtInId?<button onClick={()=>setDraft(restorePreset(draft))}>{t('ai.restoreOriginal')}</button>:<button onClick={()=>run(controller.deletePreset(draft.id).then(()=>setDraft(null)))}>{t('ai.delete')}</button>}</div></>}</fieldset>;
}
